sudo: true
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev

before_install:
  - sudo apt-add-repository ppa:sonkun/sfml-development -y
  - sudo apt-get update -qq

install: 
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705

script: 
 - ./Urho3d.sh
# - qmake GameOfLifeFighter3D.pro
# - make
 - qmake GameOfLifeFighterQt.pro
 - make
 - qmake GameOfLifeFighterSfml.pro
 - make

#after_success:
#  - codecov


