language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5  
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # SFML
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev

script: 
 - ./Urho3d.sh
# - qmake GameOfLifeFighter3D.pro
# - make
 - qmake GameOfLifeFighterQt.pro
 - make
 - qmake GameOfLifeFighterSfml.pro
 - make

#after_success:
#  - codecov


